apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://aws.github.io/eks-charts
    targetRevision: "1.1.5"
    chart: aws-load-balancer-controller
    helm:
      parameters:
        - name: clusterName
          value: {{ .Values.clusterName }}
        - name: serviceAccount.create
          value: "true"
        - name: serviceAccount.name
          value: "aws-load-balancer-controller"
        - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
          value: {{ .Values.lbRoleArn }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: aws