apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "4.9.0"
    chart: external-dns
    helm:
      parameters:
        - name: provider
          value: "aws"
        - name: registry
          value: "txt"
        - name: domainFilters
          value: {{ .Values.domainFilters }}
        - name: aws.zoneType
          value: "public"
        - name: serviceAccount.name
          value: external-dns
        - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
          value: {{ .Values.lbRoleArn }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: aws
